controller_manager:
    ros__parameters:
        update_rate: 100  # Hz
        drive_controller:
            type: velocity_controllers/JointGroupVelocityController
        joint_state_controller:
            type: joint_state_controller/JointStateController

velocity_controller:
    ros__parameters:
        joints:
            - br_axle
            - bl_axle
        interface_name: position